SELECT notes FROM northwind.purchase_orders
WHERE notes LIKE '%30'
  OR notes like '%31'
  OR notes like '%32'
  OR notes like '%33'
  OR notes like '%34'
  OR notes like '%35'
  OR notes like '%36'
  OR notes like '%37'
  OR notes like '%38'
  OR notes like '%39';